name: dmon
description: Dart Monitor for Linux
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  dbus: ^0.7.10
  flutter:
    sdk: flutter
  signals: ^5.0.0
  window_manager: ^0.3.8
  # yaru: ^1.2.1
  linux_proc:
    path: ../linux_proc
  data_table_2: ^2.5.11
  fl_chart: ^0.67.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  