name: dmon
description: Dart Monitor for Linux
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  dbus: ^0.7.10
  flutter:
    sdk: flutter
  window_manager: ^0.3.8
  # yaru: ^1.2.1
  linux_proc:
    path: ../linux_proc
  data_table_2: ^2.5.15
  fl_chart: ^0.68.0
  collection: ^1.18.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true

  